(setq-default native-comp-speed -1)
(setq comp-deferred-compilation nil)
(setq no-native-compile t)
(setq-default native-comp-bootstrap-deny-list '(".*"))

(setq load-path (cons "/vendor/lean4-mode" load-path))

(require 'lean4-mode)

(menu-bar-mode -1)
(when (boundp 'scroll-bar-mode) (scroll-bar-mode -1))
(when (and (boundp 'tool-bar-mode) (functionp 'tool-bar-mode)) (tool-bar-mode -1))
(setq inhibit-startup-screen t)
(setq show-paren-mode t)

(custom-set-faces
 '(default ((t (:foreground "#fdf6e3" :background "#002b36"))))
 '(font-lock-comment-face ((t (:foreground "#fc523f" :slant italic))))
 '(font-lock-constant-face ((t (:foreground "#2aa198"))))
 '(font-lock-warning-face ((t (:foreground "yellow" :background "#dc322f"))))
 '(font-lock-doc-face ((t (:foreground "#b58900"))))
 '(font-lock-function-name-face ((nil (:foreground "#268bd2"))))
 '(font-lock-keyword-face ((nil (:foreground "#6c61e4" :weight bold))))
 '(font-lock-string-face ((nil (:foreground "#63a363"))))
 '(font-lock-type-face ((nil (:foreground "#859900" :weight bold))))
 '(font-lock-variable-name-face ((nil (:foreground "#d33682"))))
 '(highlight ((t (:background "#ff0"))))
 '(italic ((((supports :underline t)) (:slant italic))))
 '(link ((t (:foreground "#55f" ))))
 '(region ((t (:background "#004b56"))))
 '(lazy-highlight  ((t (:background "#66305b"))))
 '(secondary-selection ((t (:background "#305b66"))))
 '(tex-verbatim ((t (:background "gray90"))))
 '(trailing-whitespace ((t (:background "#00bfbf"))))
 '(org-block ((t (:foreground "#999"))))
 '(isearch ((t (:foreground "#ffff00"))))
 '(minibuffer-prompt ((t (:foreground "#999"))))
 '(show-paren-match ((t ( :background "#007198"))))
 '(mode-line ((t (:foreground "#000000" :background "#bbbb88")))))

(setq lsp-enable-file-watchers nil)
